version: "3.5"

x-log-config: &log-config
  logging:
    driver: json-file
    options:
      max-size: "20m"
      max-file: "10"

services:
  traefik:
    image: traefik:1.7
    ports:
      - 8081:8081
    volumes:
      - traefik:/data
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - "--debug=true"
      - "--logLevel=DEBUG"
      - "--defaultentrypoints=http"
      - "--entryPoints=Name:http Address::8081"
      - "--retry"
      - "--docker.endpoint=unix:///var/run/docker.sock"
      - "--docker.watch=true"
      - "--docker.exposedbydefault=false"
    restart: always
    <<: *log-config

  vaas-api:
    image: vocdoni/vaas-api:master
    build:
      context: ../../
    env_file:
      - env
    volumes:
      - "backend-run:/app/run"
    depends_on:
      - db
    labels:
      traefik.enable: true
      traefik.frontend.rule: "PathPrefix:/api"
      traefik.default.port: 8000
      traefik.default.protocol: http
    <<: *log-config

  nginx-gw:
    image: nginx
    volumes:
      - ./gateways.json:/usr/share/nginx/html/gateways.json:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    labels:
      traefik.enable: true
      traefik.frontend.rule: "PathPrefix:/gateways.json"
      traefik.default.port: 80
      traefik.default.protocol: http
    <<: *log-config

  db:
    image: postgres:12
    env_file:
      - env
    volumes:
      - db:/data/postgres
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: "false"
    <<: *log-config

volumes:
  traefik:
  db:
  backend-run:
